### ISSUE TITLE
I am error

### ISSUE THREAD

**Issue by YifanYes** [JSotomayr/To_Do_List_React#1]
He intentado abrir tu proyecto en dos ordenadores diferentes y me sale este error.
![Error](https://user-images.githubusercontent.com/30553455/142992713-8862d4f4-4a4f-4461-965c-243de700f359.png)

**Comment by JSotomayr** [comment]
se me habia olvidado hacer el push, ya deberia estar arreglado, aunque a mi no me abre el puerto 3000
